### ISSUE TITLE
群组讨论怎么不可进了

### ISSUE THREAD

**Issue by LiuTangLei** [MapToCanada/website#37]
rt

**Comment by saullionlee66** [comment]
可能是长期没发言，被踢了了。告诉我ID，我看看。

**Comment by LiuTangLei** [comment]
> 可能是长期没发言，被踢了了。告诉我ID，我看看。

xjp willdie

**Comment by Jianxuan-Li** [comment]
> > 可能是长期没发言，被踢了了。告诉我ID，我看看。
> 
> xjp willdie

老兄，我没见过这么霸气的ID

**Comment by LiuTangLei** [comment]
> > > 可能是长期没发言，被踢了了。告诉我ID，我看看。
> > 
> > 
> > xjp willdie
> 
> 老兄，我没见过这么霸气的ID

不该用这个暴露个人信息的GitHub账号过来问的，我关issue算了
